### ISSUE TITLE
Stereo-Inertia

### ISSUE THREAD

**Issue by pengllbit** [VIS4ROB-lab/covins#26]
Does this support Stereo-Inertia,or how can I use covins to run my own Stereo-Inertia camera?

**Comment by ThomasZiegler** [comment]
Hi
Unfortunately COVINS does not support stereo. But this doesn't mean you can't run a stereo front-end in you SLAM. But when transmitting the data from your front-end to the COVINS back-end you should only transmit the keyframes of one camera. 

To implement COVINS in your own setup you need to transmit the keyframes and map points/landmarks from your front-end to the COVINS server. For this you need to transfer the keyframes and map points into messages `covins::MsgKeyframe` and `covins::MsgLandmark`, respectively. You can use our ORB SLAM 3 implementation as a guide.
https://github.com/VIS4ROB-lab/covins/blob/f8e6527bafffa5bba53a888b0e7ec625724baafe/orb_slam3/include/KeyFrame.h#L258-L272
https://github.com/VIS4ROB-lab/covins/blob/f8e6527bafffa5bba53a888b0e7ec625724baafe/orb_slam3/include/MapPoint.h#L103-L106

Regards Thomas

**Comment by pengllbit** [comment]
Thank you for your answer
I have another problem. When I use my own camera_D435i to run COVINS Mono_Inertial with ROS , it always fails to initialize. I went to see ORB_SLAM3 and failed to solve this problem. Can you give some initialization suggestions.

**Comment by pengllbit** [comment]
![covins](https://user-images.githubusercontent.com/108248618/183049993-70b310be-25a4-4b06-bc7f-36b4dc9e5bfd.png)

**Comment by pengllbit** [comment]
Fails to initialize like this
![frames set to lost](https://user-images.githubusercontent.com/108248618/183050368-eed8834a-2af3-4373-a29d-0ad8c2e00f89.png)

**Comment by ThomasZiegler** [comment]
Hi, if you have another problem please open a new dedicated issue for it. Otherwise it's hard for other people, which have similar problems to find the discussion, when it's not related to the current issue title. 

However, in your case it's seems that your new problem is very similar to issue #10. As stated there we adapted ORB SLAM 3 as front-end, but we didn't change anything in the initialization part. So to get COVINS with our front-end working you essentialy need to get ORB SLAM 3 running with your camera setup. So I would follow their [instruction](https://github.com/UZ-SLAMLab/ORB_SLAM3#4-running-orb-slam3-with-your-camera) and look in their [issues](https://github.com/UZ-SLAMLab/ORB_SLAM3/issues) if some one had similar problems or otherwise open an new issue there.

**Comment by yonggaogit** [comment]
> Fails to initialize like this ![frames set to lost](https://user-images.githubusercontent.com/108248618/183050368-eed8834a-2af3-4373-a29d-0ad8c2e00f89.png)

I encountered the same problem, did you solve it?

**Comment by patriksc** [comment]
Closing - original issue resolved
