### ISSUE TITLE
Couldn't receive the realsense camera's image

### ISSUE THREAD

**Issue by ajxdhe** [VIS4ROB-lab/covins#44]
I lanuched my realsense camera then launch the vins but vins didn't receive camera and imu data

![GphJbNmCbN](https://github.com/VIS4ROB-lab/covins/assets/92613528/8b654ef4-734d-4ac5-ba35-717cd34ac453)

![kithTCJdNM](https://github.com/VIS4ROB-lab/covins/assets/92613528/8710a8d2-65da-4856-b51e-835618bb5e36)
![ZYGMOGACuB](https://github.com/VIS4ROB-lab/covins/assets/92613528/d7ed429f-006f-46a9-a9cb-66d22a6b9f58)
![0phtkLMhtS](https://github.com/VIS4ROB-lab/covins/assets/92613528/e4bffe2a-a477-4395-851a-47d54dba03d4)

**Comment by manthan99** [comment]
Hi

You will need to remap the topics according to your agent. For example in the above case, because of the remap of the camera topics in the launch file, the VINS node expects the data to have the topic /realsense/infra1/image_rect_raw0 (For the agent 0). You will need to change this to the correct topic or alternatively you can remove the remap lines in the launch file and put the correct topic names in the VINS config file. 

Hope this helps.

Thank you
Best
Manthan

**Comment by patriksc** [comment]
Closing - inactive
